/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 27 04:37:43 GMT 2019
 */

package org.apache.commons.collections4.sequence;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.collections4.sequence.ReplacementsFinder;
import org.apache.commons.collections4.sequence.ReplacementsHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReplacementsFinder_ESTest extends ReplacementsFinder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReplacementsHandler<Object> replacementsHandler0 = (ReplacementsHandler<Object>) mock(ReplacementsHandler.class, new ViolatedAssumptionAnswer());
      ReplacementsFinder<Object> replacementsFinder0 = new ReplacementsFinder<Object>(replacementsHandler0);
      replacementsFinder0.visitInsertCommand("r;");
      replacementsFinder0.visitKeepCommand("r;");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReplacementsHandler<Object> replacementsHandler0 = (ReplacementsHandler<Object>) mock(ReplacementsHandler.class, new ViolatedAssumptionAnswer());
      ReplacementsFinder<Object> replacementsFinder0 = new ReplacementsFinder<Object>(replacementsHandler0);
      replacementsFinder0.visitKeepCommand("r;");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReplacementsFinder<String> replacementsFinder0 = new ReplacementsFinder<String>((ReplacementsHandler<String>) null);
      replacementsFinder0.visitDeleteCommand("org.apache.commons.collections4.sequence.ReplacementsFinder");
      // Undeclared exception!
      try { 
        replacementsFinder0.visitKeepCommand("org.apache.commons.collections4.sequence.ReplacementsFinder");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.sequence.ReplacementsFinder", e);
      }
  }
}
