/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 27 04:39:51 GMT 2019
 */

package org.apache.commons.collections4.functors;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections4.functors.DefaultEquator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultEquator_ESTest extends DefaultEquator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultEquator<String> defaultEquator0 = DefaultEquator.defaultEquator();
      int int0 = defaultEquator0.hash((String) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      int int0 = defaultEquator0.hash((Integer) (-1));
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultEquator<String> defaultEquator0 = DefaultEquator.defaultEquator();
      boolean boolean0 = defaultEquator0.equate("O(3U[V*x6s", "lT*0G{nh");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      boolean boolean0 = defaultEquator0.equate((Integer) (-1), (Integer) (-1));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DefaultEquator<String> defaultEquator0 = DefaultEquator.defaultEquator();
      boolean boolean0 = defaultEquator0.equate((String) null, "Ge");
      assertFalse(boolean0);
  }
}
