/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 27 03:05:16 GMT 2019
 */

package org.apache.commons.collections4.comparators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.util.LinkedList;
import java.util.List;
import org.apache.commons.collections4.comparators.FixedOrderComparator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FixedOrderComparator_ESTest extends FixedOrderComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>();
      Integer integer0 = new Integer(143);
      Integer integer1 = new Integer((-2844));
      // Undeclared exception!
      try { 
        fixedOrderComparator0.addAsEqual(integer0, integer1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 143 not known to org.apache.commons.collections4.comparators.FixedOrderComparator@82d9bfb6
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Object[] objectArray0 = new Object[4];
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(objectArray0);
      fixedOrderComparator0.compare(objectArray0[0], objectArray0[0]);
      boolean boolean0 = fixedOrderComparator0.isLocked();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FixedOrderComparator<Object>[] fixedOrderComparatorArray0 = (FixedOrderComparator<Object>[]) Array.newInstance(FixedOrderComparator.class, 1);
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      fixedOrderComparatorArray0[0] = fixedOrderComparator0;
      FixedOrderComparator<FixedOrderComparator<Object>> fixedOrderComparator1 = new FixedOrderComparator<FixedOrderComparator<Object>>(fixedOrderComparatorArray0);
      fixedOrderComparator1.compare(fixedOrderComparator0, fixedOrderComparator0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      // Undeclared exception!
      try { 
        fixedOrderComparator1.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Cannot modify a FixedOrderComparator after a comparison
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>(linkedList0);
      LinkedList<Object> linkedList1 = new LinkedList<Object>();
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(linkedList1);
      boolean boolean0 = fixedOrderComparator1.equals(fixedOrderComparator0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      boolean boolean0 = fixedOrderComparator0.equals(fixedOrderComparator0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Object[] objectArray0 = new Object[4];
      Object object0 = new Object();
      objectArray0[1] = object0;
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(objectArray0);
      fixedOrderComparator0.compare(object0, object0);
      fixedOrderComparator0.hashCode();
      assertTrue(fixedOrderComparator0.isLocked());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>();
      fixedOrderComparator0.hashCode();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Integer[] integerArray0 = new Integer[6];
      int int0 = 2;
      Integer integer0 = new Integer(2);
      integerArray0[0] = integer0;
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>(integerArray0);
      boolean boolean0 = fixedOrderComparator0.add((Integer) int0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>();
      Integer integer0 = new Integer(0);
      fixedOrderComparator0.add(integer0);
      fixedOrderComparator0.compare(integer0, integer0);
      // Undeclared exception!
      try { 
        fixedOrderComparator0.checkLocked();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Cannot modify a FixedOrderComparator after a comparison
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      boolean boolean0 = fixedOrderComparator0.isLocked();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      FixedOrderComparator<Comparable<String>> fixedOrderComparator1 = new FixedOrderComparator<Comparable<String>>();
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      boolean boolean0 = fixedOrderComparator1.equals(fixedOrderComparator0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FixedOrderComparator<Object>[] fixedOrderComparatorArray0 = (FixedOrderComparator<Object>[]) Array.newInstance(FixedOrderComparator.class, 1);
      FixedOrderComparator<FixedOrderComparator<Object>> fixedOrderComparator0 = new FixedOrderComparator<FixedOrderComparator<Object>>(fixedOrderComparatorArray0);
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      FixedOrderComparator<Integer> fixedOrderComparator1 = new FixedOrderComparator<Integer>(linkedList0);
      boolean boolean0 = fixedOrderComparator1.equals(fixedOrderComparator0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FixedOrderComparator<Comparable<Object>> fixedOrderComparator0 = new FixedOrderComparator<Comparable<Object>>();
      boolean boolean0 = fixedOrderComparator0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FixedOrderComparator<Object>[] fixedOrderComparatorArray0 = (FixedOrderComparator<Object>[]) Array.newInstance(FixedOrderComparator.class, 6);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(linkedList0);
      fixedOrderComparatorArray0[1] = fixedOrderComparator0;
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(linkedList0);
      assertTrue(fixedOrderComparator1.equals((Object)fixedOrderComparator0));
      
      FixedOrderComparator<FixedOrderComparator<Object>> fixedOrderComparator2 = new FixedOrderComparator<FixedOrderComparator<Object>>(fixedOrderComparatorArray0);
      int int0 = fixedOrderComparator2.compare(fixedOrderComparator1, fixedOrderComparatorArray0[4]);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>();
      boolean boolean0 = fixedOrderComparator0.equals("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FixedOrderComparator.UnknownObjectBehavior[] fixedOrderComparator_UnknownObjectBehaviorArray0 = FixedOrderComparator.UnknownObjectBehavior.values();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(fixedOrderComparator_UnknownObjectBehaviorArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.AFTER;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      int int0 = fixedOrderComparator0.compare(fixedOrderComparator0, fixedOrderComparator_UnknownObjectBehavior0);
      assertTrue(fixedOrderComparator0.isLocked());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FixedOrderComparator.UnknownObjectBehavior[] fixedOrderComparator_UnknownObjectBehaviorArray0 = FixedOrderComparator.UnknownObjectBehavior.values();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(fixedOrderComparator_UnknownObjectBehaviorArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.AFTER;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      Object object0 = new Object();
      int int0 = fixedOrderComparator0.compare(object0, object0);
      assertTrue(fixedOrderComparator0.isLocked());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      FixedOrderComparator<Comparable<String>> fixedOrderComparator1 = new FixedOrderComparator<Comparable<String>>();
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      FixedOrderComparator<String> fixedOrderComparator2 = new FixedOrderComparator<String>();
      int int0 = fixedOrderComparator0.compare(fixedOrderComparator1, fixedOrderComparator2);
      assertTrue(fixedOrderComparator0.isLocked());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Object[] objectArray0 = new Object[18];
      Object object0 = new Object();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(objectArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.AFTER;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      fixedOrderComparator0.compare(objectArray0[1], object0);
      // Undeclared exception!
      try { 
        fixedOrderComparator0.add(fixedOrderComparator_UnknownObjectBehavior0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Cannot modify a FixedOrderComparator after a comparison
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      Object object0 = new Object();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(objectArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      int int0 = fixedOrderComparator0.compare(objectArray0[1], object0);
      assertTrue(fixedOrderComparator0.isLocked());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      Object object0 = new Object();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(objectArray0);
      // Undeclared exception!
      try { 
        fixedOrderComparator0.compare(objectArray0[1], object0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Attempting to compare unknown object java.lang.Object@76eeee8c
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      FixedOrderComparator.UnknownObjectBehavior[] fixedOrderComparator_UnknownObjectBehaviorArray0 = FixedOrderComparator.UnknownObjectBehavior.values();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(fixedOrderComparator_UnknownObjectBehaviorArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      // Undeclared exception!
      try { 
        fixedOrderComparator0.compare(fixedOrderComparator0, fixedOrderComparator_UnknownObjectBehavior0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Attempting to compare unknown object org.apache.commons.collections4.comparators.FixedOrderComparator@959aa5c
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Object[] objectArray0 = new Object[8];
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(objectArray0);
      Object object0 = new Object();
      boolean boolean0 = fixedOrderComparator0.addAsEqual(objectArray0[2], object0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "e";
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>(stringArray0);
      boolean boolean0 = fixedOrderComparator0.addAsEqual("e", "e");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Integer integer0 = new Integer((-2371));
      Object[] objectArray0 = new Object[3];
      objectArray0[1] = (Object) integer0;
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(objectArray0);
      fixedOrderComparator0.compare(integer0, objectArray0[1]);
      // Undeclared exception!
      try { 
        fixedOrderComparator0.addAsEqual((Object) null, objectArray0[0]);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Cannot modify a FixedOrderComparator after a comparison
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(770);
      linkedList0.offer(integer0);
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(linkedList0);
      assertFalse(fixedOrderComparator0.isLocked());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      FixedOrderComparator<Integer> fixedOrderComparator0 = null;
      try {
        fixedOrderComparator0 = new FixedOrderComparator<Integer>((List<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The list of items must not be null
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>(linkedList0);
      // Undeclared exception!
      try { 
        fixedOrderComparator0.setUnknownObjectBehavior((FixedOrderComparator.UnknownObjectBehavior) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Unknown object behavior must not be null
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      FixedOrderComparator<String> fixedOrderComparator0 = null;
      try {
        fixedOrderComparator0 = new FixedOrderComparator<String>((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The list of items must not be null
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      FixedOrderComparator.UnknownObjectBehavior[] fixedOrderComparator_UnknownObjectBehaviorArray0 = FixedOrderComparator.UnknownObjectBehavior.values();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(fixedOrderComparator_UnknownObjectBehaviorArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      int int0 = fixedOrderComparator0.compare(fixedOrderComparator0, fixedOrderComparator_UnknownObjectBehavior0);
      assertTrue(fixedOrderComparator0.isLocked());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      fixedOrderComparator0.checkLocked();
      assertFalse(fixedOrderComparator0.isLocked());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      fixedOrderComparator0.getUnknownObjectBehavior();
      assertFalse(fixedOrderComparator0.isLocked());
  }
}
